package uam.mx.Servicios;

import java.util.Collection;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import uam.mx.Negocio.LlaveAccesoService;
import uam.mx.Negocio.Dominio.LlaveAcceso;

@RestController    // This means that this class is a Controller
@RequestMapping(path="/llavesRC") // This means URL's start with /demo (after Application path)
public class LlaveAccesoController {
	@Autowired // This means to get the bean called LlaveAccesoRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private LlaveAccesoService llaveAccesoService;
	
	@RequestMapping(value="/")
	public String holaMundo() {
		return "<h1>Hola, Soy el sistema llaves<h1>";
	}
	
	@GetMapping(path="/add") // Map ONLY GET Requests
	public ResponseEntity<LlaveAcceso> addNewLlaveAcceso (@RequestParam String rol) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		LlaveAcceso ll = new LlaveAcceso(rol);
		boolean retorno = llaveAccesoService.addNewLlaveAcceso(ll);
        if(retorno) {
            return new ResponseEntity<LlaveAcceso>(ll, HttpStatus.CREATED);
        } else {
            return new ResponseEntity<LlaveAcceso>(ll, HttpStatus.BAD_REQUEST);
        }
	}
	
	@GetMapping(path="/all")
	public Collection <LlaveAcceso> getAllLlaveAccesos() {
		// This returns a JSON or XML with the LlaveAccesos
		return llaveAccesoService.getLlaves();
	}
}
